-- ============================================================
-- PTE Management System — Oracle 23ai DDL
-- Run as: hr@localhost/FREEPDB1
-- ============================================================

-- ------------------------------------------------------------
-- SEQUENCES
-- ------------------------------------------------------------
CREATE SEQUENCE SEQ_USER      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TOKEN     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SUBJECT   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GRADE     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PARENT    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STUDENT   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CLASS     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SCHEDULE  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SESSION   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ATTENDANCE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INVOICE   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INVOICE_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAYMENT   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ------------------------------------------------------------
-- USERS (base table — OWNER, ADMIN, TUTOR)
-- ------------------------------------------------------------
CREATE TABLE USERS (
    USER_ID         NUMBER          DEFAULT SEQ_USER.NEXTVAL PRIMARY KEY,
    FULLNAME        VARCHAR2(150)   NOT NULL,
    EMAIL           VARCHAR2(200)   NOT NULL UNIQUE,
    PHONE           VARCHAR2(20),
    PASSWORD_HASH   VARCHAR2(255)   NOT NULL,
    ROLE            VARCHAR2(10)    NOT NULL,
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    SUPERVISOR_ID   NUMBER,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_USERS_ROLE CHECK (ROLE IN ('OWNER', 'ADMIN', 'TUTOR')),
    CONSTRAINT CHK_USERS_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT FK_USERS_SUPERVISOR FOREIGN KEY (SUPERVISOR_ID) REFERENCES USERS (USER_ID)
);

-- ------------------------------------------------------------
-- SUBTYPE PROFILE TABLES (ISA pattern)
-- ------------------------------------------------------------
CREATE TABLE OWNER_PROFILE (
    USER_ID         NUMBER          PRIMARY KEY,
    BUSINESS_REG    VARCHAR2(50),
    CONSTRAINT FK_OWNER_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE ADMIN_PROFILE (
    USER_ID         NUMBER          PRIMARY KEY,
    DEPARTMENT      VARCHAR2(100),
    CONSTRAINT FK_ADMIN_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE TUTOR_PROFILE (
    USER_ID         NUMBER          PRIMARY KEY,
    QUALIFICATION   VARCHAR2(200),
    SPECIALISATION  VARCHAR2(200),
    CONSTRAINT FK_TUTOR_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- PASSWORD RESET TOKENS
-- ------------------------------------------------------------
CREATE TABLE PASSWORD_RESET_TOKEN (
    TOKEN_ID        NUMBER          DEFAULT SEQ_TOKEN.NEXTVAL PRIMARY KEY,
    USER_ID         NUMBER          NOT NULL,
    TOKEN           VARCHAR2(255)   NOT NULL UNIQUE,
    EXPIRES_AT      TIMESTAMP       NOT NULL,
    USED            NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PRT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_PRT_USED CHECK (USED IN (0, 1))
);

-- ------------------------------------------------------------
-- SUBJECT
-- ------------------------------------------------------------
CREATE TABLE SUBJECT (
    SUBJECT_ID      NUMBER          DEFAULT SEQ_SUBJECT.NEXTVAL PRIMARY KEY,
    NAME            VARCHAR2(150)   NOT NULL,
    CODE            VARCHAR2(20)    NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR2(500),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

-- ------------------------------------------------------------
-- GRADE
-- ------------------------------------------------------------
CREATE TABLE GRADE (
    GRADE_ID        NUMBER          DEFAULT SEQ_GRADE.NEXTVAL PRIMARY KEY,
    NAME            VARCHAR2(100)   NOT NULL,
    GRADE_LEVEL     NUMBER          NOT NULL,
    DESCRIPTION     VARCHAR2(300),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

-- ------------------------------------------------------------
-- PARENT
-- ------------------------------------------------------------
CREATE TABLE PARENT (
    PARENT_ID       NUMBER          DEFAULT SEQ_PARENT.NEXTVAL PRIMARY KEY,
    FULLNAME        VARCHAR2(150)   NOT NULL,
    IC_NUMBER       VARCHAR2(20)    UNIQUE,
    EMAIL           VARCHAR2(200),
    PHONE           VARCHAR2(20)    NOT NULL,
    ADDRESS         VARCHAR2(500),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

-- ------------------------------------------------------------
-- STUDENT
-- ------------------------------------------------------------
CREATE TABLE STUDENT (
    STUDENT_ID      NUMBER          DEFAULT SEQ_STUDENT.NEXTVAL PRIMARY KEY,
    FULLNAME        VARCHAR2(150)   NOT NULL,
    IC_NUMBER       VARCHAR2(20)    UNIQUE,
    PHONE           VARCHAR2(20),
    STATUS          VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL,
    GRADE_ID        NUMBER          NOT NULL,
    PARENT_ID       NUMBER          NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_STUDENT_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT FK_STUDENT_GRADE  FOREIGN KEY (GRADE_ID)  REFERENCES GRADE  (GRADE_ID),
    CONSTRAINT FK_STUDENT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PARENT (PARENT_ID)
);

-- ------------------------------------------------------------
-- CLASS
-- ------------------------------------------------------------
CREATE TABLE CLASS (
    CLASS_ID        NUMBER          DEFAULT SEQ_CLASS.NEXTVAL PRIMARY KEY,
    NAME            VARCHAR2(150)   NOT NULL,
    SUBJECT_ID      NUMBER          NOT NULL,
    GRADE_ID        NUMBER          NOT NULL,
    USER_ID         NUMBER          NOT NULL,
    FEE             NUMBER(10, 2)   NOT NULL,
    MAX_STUDENTS    NUMBER          DEFAULT 30,
    STATUS          VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_CLASS_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT FK_CLASS_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT (SUBJECT_ID),
    CONSTRAINT FK_CLASS_GRADE   FOREIGN KEY (GRADE_ID)   REFERENCES GRADE   (GRADE_ID),
    CONSTRAINT FK_CLASS_TUTOR   FOREIGN KEY (USER_ID)    REFERENCES USERS   (USER_ID)
);

-- ------------------------------------------------------------
-- CLASS_SCHEDULE (recurring template)
-- ------------------------------------------------------------
CREATE TABLE CLASS_SCHEDULE (
    SCHEDULE_ID     NUMBER          DEFAULT SEQ_SCHEDULE.NEXTVAL PRIMARY KEY,
    CLASS_ID        NUMBER          NOT NULL,
    DAYSOFWEEK      VARCHAR2(3)     NOT NULL,
    START_TIME      VARCHAR2(5)     NOT NULL,
    END_TIME        VARCHAR2(5)     NOT NULL,
    EFFECTIVE_FROM  DATE            NOT NULL,
    EFFECTIVE_TO    DATE,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_SCHEDULE_DAY CHECK (DAYSOFWEEK IN ('MON','TUE','WED','THU','FRI','SAT','SUN')),
    CONSTRAINT FK_SCHEDULE_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASS (CLASS_ID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- CLASS_SESSION (generated instance from schedule)
-- ------------------------------------------------------------
CREATE TABLE CLASS_SESSION (
    SESSION_ID      NUMBER          DEFAULT SEQ_SESSION.NEXTVAL PRIMARY KEY,
    CLASS_ID        NUMBER          NOT NULL,
    SCHEDULE_ID     NUMBER,
    USER_ID         NUMBER          NOT NULL,
    SESSION_DATE    DATE            NOT NULL,
    START_TIME      VARCHAR2(5)     NOT NULL,
    END_TIME        VARCHAR2(5)     NOT NULL,
    STATUS          VARCHAR2(15)    DEFAULT 'SCHEDULED' NOT NULL,
    NOTES           VARCHAR2(500),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_SESSION_STATUS CHECK (STATUS IN ('SCHEDULED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT FK_SESSION_CLASS    FOREIGN KEY (CLASS_ID)    REFERENCES CLASS         (CLASS_ID),
    CONSTRAINT FK_SESSION_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES CLASS_SCHEDULE (SCHEDULE_ID),
    CONSTRAINT FK_SESSION_USER     FOREIGN KEY (USER_ID)     REFERENCES USERS          (USER_ID)
);

-- ------------------------------------------------------------
-- CLASS_STUDENT (M:N enrolment bridge)
-- ------------------------------------------------------------
CREATE TABLE CLASS_STUDENT (
    CLASS_ID        NUMBER          NOT NULL,
    STUDENT_ID      NUMBER          NOT NULL,
    ENROLLED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CLASS_STUDENT    PRIMARY KEY (CLASS_ID, STUDENT_ID),
    CONSTRAINT FK_CS_CLASS         FOREIGN KEY (CLASS_ID)   REFERENCES CLASS   (CLASS_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CS_STUDENT       FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- STUDENT_ATTENDANCE
-- ------------------------------------------------------------
CREATE TABLE STUDENT_ATTENDANCE (
    ATTENDANCE_ID   NUMBER          DEFAULT SEQ_ATTENDANCE.NEXTVAL PRIMARY KEY,
    SESSION_ID      NUMBER          NOT NULL,
    STUDENT_ID      NUMBER          NOT NULL,
    STATUS          VARCHAR2(10)    NOT NULL,
    REMARKS         VARCHAR2(300),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_ATTENDANCE_STATUS CHECK (STATUS IN ('PRESENT', 'ABSENT', 'LATE')),
    CONSTRAINT UQ_ATTENDANCE        UNIQUE (SESSION_ID, STUDENT_ID),
    CONSTRAINT FK_ATT_SESSION       FOREIGN KEY (SESSION_ID)  REFERENCES CLASS_SESSION (SESSION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ATT_STUDENT       FOREIGN KEY (STUDENT_ID)  REFERENCES STUDENT       (STUDENT_ID)
);

-- ------------------------------------------------------------
-- INVOICE
-- ------------------------------------------------------------
CREATE TABLE INVOICE (
    INVOICE_ID      NUMBER          DEFAULT SEQ_INVOICE.NEXTVAL PRIMARY KEY,
    PARENT_ID       NUMBER          NOT NULL,
    BILLING_MONTH   NUMBER(2)       NOT NULL,
    BILLING_YEAR    NUMBER(4)       NOT NULL,
    TOTAL_AMOUNT    NUMBER(10, 2)   NOT NULL,
    STATUS          VARCHAR2(10)    DEFAULT 'UNPAID' NOT NULL,
    DUE_DATE        DATE            NOT NULL,
    NOTES           VARCHAR2(500),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_INVOICE_STATUS   CHECK (STATUS IN ('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE')),
    CONSTRAINT CHK_INVOICE_MONTH    CHECK (BILLING_MONTH BETWEEN 1 AND 12),
    CONSTRAINT UQ_INVOICE_PARENT_MONTH UNIQUE (PARENT_ID, BILLING_MONTH, BILLING_YEAR),
    CONSTRAINT FK_INVOICE_PARENT    FOREIGN KEY (PARENT_ID) REFERENCES PARENT (PARENT_ID)
);

-- ------------------------------------------------------------
-- INVOICE_ITEM
-- ------------------------------------------------------------
CREATE TABLE INVOICE_ITEM (
    ITEM_ID         NUMBER          DEFAULT SEQ_INVOICE_ITEM.NEXTVAL PRIMARY KEY,
    INVOICE_ID      NUMBER          NOT NULL,
    STUDENT_ID      NUMBER          NOT NULL,
    CLASS_ID        NUMBER          NOT NULL,
    DESCRIPTION     VARCHAR2(300)   NOT NULL,
    AMOUNT          NUMBER(10, 2)   NOT NULL,
    CONSTRAINT FK_ITEM_INVOICE  FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_STUDENT  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID),
    CONSTRAINT FK_ITEM_CLASS    FOREIGN KEY (CLASS_ID)   REFERENCES CLASS   (CLASS_ID)
);

-- ------------------------------------------------------------
-- PAYMENT
-- ------------------------------------------------------------
CREATE TABLE PAYMENT (
    PAYMENT_ID      NUMBER          DEFAULT SEQ_PAYMENT.NEXTVAL PRIMARY KEY,
    INVOICE_ID      NUMBER          NOT NULL,
    AMOUNT_PAID     NUMBER(10, 2)   NOT NULL,
    METHOD          VARCHAR2(20)    NOT NULL,
    PAYMENT_DATE    DATE            DEFAULT SYSDATE NOT NULL,
    REFERENCE_NO    VARCHAR2(100),
    NOTES           VARCHAR2(300),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_PAYMENT_METHOD CHECK (METHOD IN ('CASH', 'BANK_TRANSFER', 'ONLINE', 'CHEQUE')),
    CONSTRAINT FK_PAYMENT_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID)
);

-- ------------------------------------------------------------
-- INDEXES
-- ------------------------------------------------------------
CREATE INDEX IDX_USERS_ROLE           ON USERS (ROLE);
CREATE INDEX IDX_STUDENT_GRADE        ON STUDENT (GRADE_ID);
CREATE INDEX IDX_STUDENT_PARENT       ON STUDENT (PARENT_ID);
CREATE INDEX IDX_CLASS_SUBJECT        ON CLASS (SUBJECT_ID);
CREATE INDEX IDX_CLASS_GRADE          ON CLASS (GRADE_ID);
CREATE INDEX IDX_CLASS_TUTOR          ON CLASS (USER_ID);
CREATE INDEX IDX_SESSION_CLASS        ON CLASS_SESSION (CLASS_ID);
CREATE INDEX IDX_SESSION_DATE         ON CLASS_SESSION (SESSION_DATE);
CREATE INDEX IDX_ATTENDANCE_SESSION   ON STUDENT_ATTENDANCE (SESSION_ID);
CREATE INDEX IDX_INVOICE_PARENT       ON INVOICE (PARENT_ID);
CREATE INDEX IDX_INVOICE_STATUS       ON INVOICE (STATUS);
CREATE INDEX IDX_PAYMENT_INVOICE      ON PAYMENT (INVOICE_ID);

-- ------------------------------------------------------------
-- SEED: default OWNER account
-- Password: Admin@1234  (bcrypt — regenerate before production)
-- ------------------------------------------------------------
INSERT INTO USERS (FULLNAME, EMAIL, PHONE, PASSWORD_HASH, ROLE)
VALUES (
    'System Owner',
    'owner@pte.edu.my',
    '0123456789',
    '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
    'OWNER'
);

INSERT INTO OWNER_PROFILE (USER_ID, BUSINESS_REG)
VALUES (SEQ_USER.CURRVAL, 'REG-000001');

COMMIT;
