-- ============================================================
-- PTE Management System — Full Reset
-- Run this BEFORE re-running ddl.sql + seed.sql
-- Drops all tables and sequences, then lets ddl.sql recreate them
-- ============================================================

-- Disable constraints temporarily by dropping in reverse FK order
DROP TABLE PAYMENT              CASCADE CONSTRAINTS;
DROP TABLE INVOICE_ITEM         CASCADE CONSTRAINTS;
DROP TABLE INVOICE              CASCADE CONSTRAINTS;
DROP TABLE STUDENT_ATTENDANCE   CASCADE CONSTRAINTS;
DROP TABLE CLASS_STUDENT        CASCADE CONSTRAINTS;
DROP TABLE CLASS_SESSION        CASCADE CONSTRAINTS;
DROP TABLE CLASS_SCHEDULE       CASCADE CONSTRAINTS;
DROP TABLE CLASS                CASCADE CONSTRAINTS;
DROP TABLE STUDENT              CASCADE CONSTRAINTS;
DROP TABLE PARENT               CASCADE CONSTRAINTS;
DROP TABLE PASSWORD_RESET_TOKEN CASCADE CONSTRAINTS;
DROP TABLE TUTOR_PROFILE        CASCADE CONSTRAINTS;
DROP TABLE ADMIN_PROFILE        CASCADE CONSTRAINTS;
DROP TABLE OWNER_PROFILE        CASCADE CONSTRAINTS;
DROP TABLE USERS                CASCADE CONSTRAINTS;
DROP TABLE SUBJECT              CASCADE CONSTRAINTS;
DROP TABLE GRADE                CASCADE CONSTRAINTS;

-- Drop all sequences
DROP SEQUENCE SEQ_USER;
DROP SEQUENCE SEQ_TOKEN;
DROP SEQUENCE SEQ_SUBJECT;
DROP SEQUENCE SEQ_GRADE;
DROP SEQUENCE SEQ_PARENT;
DROP SEQUENCE SEQ_STUDENT;
DROP SEQUENCE SEQ_CLASS;
DROP SEQUENCE SEQ_SCHEDULE;
DROP SEQUENCE SEQ_SESSION;
DROP SEQUENCE SEQ_ATTENDANCE;
DROP SEQUENCE SEQ_INVOICE;
DROP SEQUENCE SEQ_INVOICE_ITEM;
DROP SEQUENCE SEQ_PAYMENT;

COMMIT;
